version: "3.9"
services:
  ragnar-app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - ollama
  ollama:
    image: ollama/ollama
    ports:
      - "5000:5000"  # Adjust based on Ollama's default port
